return require('packer').startup(function()
    use 'wbthomason/packer.nvim'
    use 'overcache/NeoSolarized'
--    use 'morhetz/gruvbox'
--    use 'w0ng/vim-hybrid'
    use 'mhinz/vim-startify'
    use 'vim-airline/vim-airline'
    use 'vim-airline/vim-airline-themes'
    use 'Raimondi/delimitMate'
--    use 'yggdroot/indentline'
--    use 'scrooloose/nerdtree'
--    use 'ryanoasis/vim-devicons'
--    use 'kien/ctrlp.vim'
--    use 'brooth/far.vim'
--    use 'justinmk/vim-syntax-extra'
--    use 'tbastos/vim-lua'
--    use 'pprovost/vim-ps1'
--    use 'octol/vim-cpp-enhanced-highlight'
end)
